# Generated by Django 3.0.5 on 2020-05-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200522_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cetagery',
            new_name='category',
        ),
    ]
